export const pokemon = {
  FETCH_POKEMON: "FETCH_POKEMON",
  SET_POKEMON: "SET_POKEMON",
  LOAD_POKEMON: "LOAD_POKEMON",
};
export const singlePokemon = {
  LOAD_SINGLE_POKEMON: "LOAD_SINGLE_POKEMON",
  FETCH_SINGLE_POKEMON: "FETCH_SINGLE_POKEMON",
  SET_SINGLE_POKEMON: "SET_SINGLE_POKEMON",
};
